# Generated by Django 6.0.1 on 2026-01-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='task',
            field=models.TextField(default='some text', verbose_name='Задание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='Теория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование урока'),
        ),
    ]
